// ---- PORTFOLIO DATA ----
// Edit project copy, images, and meta here. Image paths are relative to /images/<project-slug>/

const CATEGORIES = [
  {
    slug: "social-impact",
    icon: "blue",
    title: "Social Impact &<br>Feminist Organisations",
    short: "Brand, editorial, and campaign design for NGOs and feminist publications.",
    eyebrow: "Social impact",
    desc: "Brand identity, editorial design, and campaign visuals for organisations working on gender justice, reproductive rights, and civic education across Africa.",
  },
  {
    slug: "childrens-books",
    icon: "lime",
    title: "Children's Books &<br>Illustration",
    short: "Hand-drawn illustration and layout for young readers.",
    eyebrow: "Illustration",
    desc: "Character illustration and page layout for children's storytelling — building visual worlds that are warm, clear, and built to hold a child's attention.",
  },
  {
    slug: "brand-business",
    icon: "black",
    title: "Brand &<br>Business Design",
    short: "Identity systems and packaging for podcasts, cafés, and small businesses.",
    eyebrow: "Brand design",
    desc: "Logo, identity, and packaging design for independent brands, podcasts, and businesses building a presence from the ground up.",
  },
];

const PROJECTS = [
  // ---------------- SOCIAL IMPACT & FEMINIST ORGANISATIONS ----------------
  {
    slug: "feminist-in-kenya",
    category: "social-impact",
    title: "Feminists in Kenya — Magazine & Website Design",
    tag: "Editorial + Web",
    client: "Feminists in Kenya (FIK)",
    role: "Editorial design, layout, web design",
    type: "Print & digital",
    cover: "images/feminist-in-kenya/issue-02/feminist-futures.jpg",
    desc: "Layout and visual identity for FIK's digital magazine, designed to give long-form feminist writing and reporting a reading experience as considered as the ideas inside it. Each issue balances dense editorial content with imagery that keeps the publication feeling current and accessible, alongside a companion website built to host and archive the magazine's growing back catalogue.",
    gallery: [
      { type: "image", src: "images/feminist-in-kenya/issue-02/feminist-futures.jpg", caption: "Issue 02 — Feminist Futures, cover design" },
      { type: "image", src: "images/feminist-in-kenya/issue-02/issue-22.jpg" },
      { type: "image", src: "images/feminist-in-kenya/issue-02/issue-24.jpg" },
      { type: "image", src: "images/feminist-in-kenya/issue-02/issue-27.jpg" },
      { type: "image", src: "images/feminist-in-kenya/issue-01/psd-1.png", caption: "Issue 01 spreads" },
      { type: "image", src: "images/feminist-in-kenya/issue-01/psd-3.png" },
      { type: "mockup", desktop: "images/feminist-in-kenya/website/hero.png", mobile: null, caption: "FIK website — homepage" },
      { type: "image", src: "images/feminist-in-kenya/website/fik-website.png" },
    ],
  },
  {
    slug: "ipas",
    category: "social-impact",
    title: "Ipas Africa Alliance — Campaign Illustration",
    tag: "Illustration + Campaign",
    client: "Ipas Africa Alliance",
    role: "Illustration, campaign visuals",
    type: "Digital campaign",
    cover: "images/ipas/ipas-mockup.png",
    desc: "Illustrated campaign visuals for Ipas Africa Alliance, addressing sensitive themes — child marriage, reproductive rights, and girls' futures — with imagery built to communicate clearly across audiences and platforms without sacrificing nuance or dignity.",
    gallery: [
      { type: "image", src: "images/ipas/ipas-mockup.png" },
      { type: "image", src: "images/ipas/child-marriage.png" },
      { type: "image", src: "images/ipas/2-possible-futures-for-girls.png" },
      { type: "image", src: "images/ipas/classroom-2.png" },
    ],
  },
  {
    slug: "unaids",
    category: "social-impact",
    title: "UNAIDS — Factsheet & Report Design",
    tag: "Editorial Design",
    client: "UNAIDS",
    role: "Layout, data visualisation",
    type: "Print & digital reports",
    cover: "images/unaids/zambia-factsheet-pdf.png",
    desc: "Design and layout for UNAIDS country factsheets and reports, translating dense public health data into formats that are legible and usable for policymakers, partners, and the public.",
    gallery: [
      { type: "image", src: "images/unaids/zambia-factsheet-pdf.png" },
      { type: "image", src: "images/unaids/35e056157531291-637cbb92b722b.png" },
      { type: "image", src: "images/unaids/5c9858157531291-637cbb92b9996.jpg" },
      { type: "image", src: "images/unaids/678a9b157531291-637cbb92b7f75.png" },
      { type: "image", src: "images/unaids/d81471157531291-637cbb92b8cf6.png" },
    ],
  },
  {
    slug: "akina-mama-wa-afrika",
    category: "social-impact",
    title: "Akina Mama wa Afrika — Report Cover Design",
    tag: "Editorial Design",
    client: "Akina Mama wa Afrika",
    role: "Cover & report design",
    type: "Print & digital report",
    cover: "images/akina-mama/feminist-approaches-to-abortion-rights-in-uganda.png",
    desc: "Cover and report design for Akina Mama wa Afrika's research on feminist approaches to abortion rights in Uganda — visual treatment built to carry the weight of the subject while staying accessible to a wide policy and advocacy audience.",
    gallery: [
      { type: "image", src: "images/akina-mama/feminist-approaches-to-abortion-rights-in-uganda.png" },
    ],
  },
  {
    slug: "lgli",
    category: "social-impact",
    title: "Let Girls Learn Initiative — Website Design",
    tag: "Web Design",
    client: "Let Girls Learn Initiative (LGLI)",
    role: "Web design (desktop + mobile)",
    type: "Website",
    cover: "images/lgli/screencapture-letgirlslearnke-org-2026-04-10-10-00-26.png",
    desc: "Full website design for Let Girls Learn Initiative, built to present the organisation's advocacy work clearly to funders, partners, and the public — with equal attention given to how the site reads and functions on mobile, where most of LGLI's audience in Kenya accesses it.",
    gallery: [
      {
        type: "mockup-row",
        desktop: "images/lgli/screencapture-letgirlslearnke-org-2026-04-10-10-00-26.png",
        mobile: "images/lgli/letgirlslearnke-org-mobile.png",
        caption: "Homepage — desktop & mobile",
      },
      { type: "image", src: "images/lgli/screencapture-letgirlslearnke-org-about-us-2026-04-10-10-01-15.png", caption: "About page" },
      { type: "image", src: "images/lgli/screencapture-letgirlslearnke-org-advocacy-2026-04-10-10-01-29.png", caption: "Advocacy page" },
    ],
  },
  {
    slug: "the-50-percent",
    category: "social-impact",
    title: "The 50 Percent — Young People's Guide Illustration & Layout",
    tag: "Illustration + Layout",
    client: "The 50 Percent",
    role: "Illustration, digital book layout",
    type: "Digital publication",
    cover: "images/the-50-percent/1.png",
    desc: "Illustration and full digital layout for The 50 Percent's young people's guide — designed to make complex, sometimes difficult topics approachable for a younger readership through warm illustration and a page rhythm built for screen reading.",
    gallery: [
      { type: "image", src: "images/the-50-percent/1.png" },
      { type: "image", src: "images/the-50-percent/2.png" },
      { type: "image", src: "images/the-50-percent/3.png" },
      { type: "image", src: "images/the-50-percent/4.png" },
      { type: "image", src: "images/the-50-percent/5.png" },
      { type: "image", src: "images/the-50-percent/6.png" },
      { type: "image", src: "images/the-50-percent/7.png" },
    ],
  },
  {
    slug: "debunk-media",
    category: "social-impact",
    title: "Debunk Media — Website Redesign",
    tag: "Web Design · WAN-IFRA Silver Award",
    client: "Debunk Media",
    role: "Lead designer — full website redesign",
    type: "Website",
    cover: "images/debunk-media/debunk-media-website.png",
    desc: "Full redesign of Debunk Media's website, rebuilt from the ground up to better serve readers navigating fact-checked journalism — clearer information hierarchy, a stronger archive experience, and a visual identity that matched the seriousness of the reporting. The redesign, \"Beyond the Headline,\" won a WAN-IFRA Silver Award.",
    gallery: [
      { type: "image", src: "images/debunk-media/debunk-media-website.png", caption: "Final homepage design" },
      { type: "image", src: "images/debunk-media/screencapture-debunk-media-archive-2026-04-10-10-03-45.png", caption: "Article archive" },
      { type: "image", src: "images/debunk-media/figma-wireframe.png", caption: "Early wireframe — process" },
    ],
  },

  // ---------------- CHILDREN'S BOOKS & ILLUSTRATION ----------------
  {
    slug: "arthur-goes-potty",
    category: "childrens-books",
    title: "Arthur Goes Potty — Children's Book Illustration",
    tag: "Illustration",
    client: "Children's book project",
    role: "Character illustration, page art",
    type: "Print / digital children's book",
    cover: "images/arthur-goes-potty/front-page.png",
    desc: "Full character illustration for a children's book built around a milestone every toddler faces — potty training. The brief called for art that's warm and funny without being twee, with a character expressive enough to carry an early reader through a story largely told in pictures.",
    gallery: [
      { type: "image", src: "images/arthur-goes-potty/front-page.png", caption: "Cover" },
      { type: "image", src: "images/arthur-goes-potty/08.png" },
      { type: "image", src: "images/arthur-goes-potty/09.png" },
      { type: "image", src: "images/arthur-goes-potty/10.png" },
    ],
  },

  // ---------------- BRAND & BUSINESS DESIGN ----------------
  {
    slug: "digital-dada",
    category: "brand-business",
    title: "Digital Dada — Website Design",
    tag: "Web Design",
    client: "Digital Dada",
    role: "Web design (desktop + mobile)",
    type: "Website",
    cover: "images/digital-dada/digitaldada-website.png",
    desc: "Website design for Digital Dada, built with a layout that holds up cleanly across screen sizes — from a full desktop browsing experience down to a mobile view designed for on-the-go listeners and visitors.",
    gallery: [
      {
        type: "mockup-row",
        desktop: "images/digital-dada/digitaldada-website.png",
        mobile: "images/digital-dada/digital-dada-website-mobile.png",
        caption: "Homepage — desktop & mobile",
      },
    ],
  },
  {
    slug: "data-and-potatoes",
    category: "brand-business",
    title: "Data and Potatoes — Podcast Brand Identity",
    tag: "Brand Identity",
    client: "Data and Potatoes",
    role: "Brand identity, social templates",
    type: "Brand identity",
    cover: "images/data-and-potatoes/artboard-1.jpg",
    desc: "Brand identity for the Data and Potatoes podcast — a visual language playful enough to match the show's tone while staying flexible across episode art, social templates, and promotional assets.",
    gallery: [
      { type: "image", src: "images/data-and-potatoes/artboard-1.jpg" },
      { type: "image", src: "images/data-and-potatoes/artboard-2.jpg" },
      { type: "image", src: "images/data-and-potatoes/artboard-3.jpg" },
      { type: "image", src: "images/data-and-potatoes/artboard-4.jpg" },
      { type: "image", src: "images/data-and-potatoes/artboard-5.jpg" },
    ],
  },
  {
    slug: "sweeven-cafe",
    category: "brand-business",
    title: "Sweeven Café — Brand Identity",
    tag: "Brand Identity",
    client: "Sweeven Café",
    role: "Logo design, brand identity",
    type: "Brand identity",
    cover: "images/sweeven/sweeven.png",
    desc: "Logo and brand identity for Sweeven Café, designed to feel warm and inviting in a physical space while translating cleanly onto packaging, signage, and social media.",
    gallery: [
      { type: "image", src: "images/sweeven/sweeven-logo.png", caption: "Primary logo" },
      { type: "image", src: "images/sweeven/sweeven.png" },
      { type: "image", src: "images/sweeven/artboard-1.png" },
      { type: "image", src: "images/sweeven/artboard-2.png" },
      { type: "image", src: "images/sweeven/artboard-3.png" },
    ],
  },
  {
    slug: "so-this-is-love",
    category: "brand-business",
    title: "So This Is Love — Podcast Brand Identity",
    tag: "Brand Identity",
    client: "So This Is Love",
    role: "Brand identity, episode art system",
    type: "Brand identity",
    cover: "images/so-this-is-love/artboard-2-copy.png",
    desc: "Brand identity for the So This Is Love podcast — an identity system built around an intimate, conversational tone, with a flexible art direction that holds up across episode covers and promotional content.",
    gallery: [
      { type: "image", src: "images/so-this-is-love/artboard-2-copy.png" },
      { type: "image", src: "images/so-this-is-love/artboard-3-copy.png" },
      { type: "image", src: "images/so-this-is-love/artboard-4-copy.png" },
    ],
  },
  {
    slug: "tricias-naturals",
    category: "brand-business",
    title: "Tricia's Naturals — Product Packaging",
    tag: "Packaging Design",
    client: "Tricia's Naturals",
    role: "Product packaging design",
    type: "Packaging",
    cover: "images/tricias-naturals/image.png",
    desc: "Product packaging design for Tricia's Naturals' natural hair care line, built to stand out on shelf while communicating the brand's natural, locally-rooted positioning at a glance.",
    gallery: [
      { type: "image", src: "images/tricias-naturals/image.png" },
      { type: "image", src: "images/tricias-naturals/image-1.png" },
      { type: "image", src: "images/tricias-naturals/image-2.png" },
      { type: "image", src: "images/tricias-naturals/happylocs-beginner.jpg" },
      { type: "image", src: "images/tricias-naturals/121584851-3411691868876681-4986800071277286453-o.jpg" },
    ],
  },
];
